# Generated by Django 4.1.4 on 2022-12-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('week_work', models.IntegerField()),
                ('day_work', models.IntegerField()),
                ('job', models.CharField(max_length=20)),
                ('annual', models.IntegerField()),
                ('sex', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
