# Generated by Django 4.1.4 on 2022-12-27 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='annual',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Wollu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField()),
                ('all_time', models.IntegerField()),
                ('no_work', models.IntegerField(null=True)),
                ('coffe', models.IntegerField(null=True)),
                ('toilet', models.IntegerField(null=True)),
                ('wind', models.IntegerField(null=True)),
                ('shopping', models.IntegerField(null=True)),
                ('smoking', models.IntegerField(null=True)),
                ('something', models.IntegerField(null=True)),
                ('turnover', models.IntegerField(null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
