# Generated by Django 4.1.4 on 2022-12-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_age_alter_user_annual_alter_user_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wollu',
            name='coffe',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wollu',
            name='no_work',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wollu',
            name='shopping',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wollu',
            name='smoking',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wollu',
            name='something',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wollu',
            name='toilet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wollu',
            name='turnover',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wollu',
            name='wind',
            field=models.IntegerField(default=0),
        ),
    ]
