# Generated by Django 4.1.4 on 2022-12-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_user_id_wollu_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wollu',
            name='coffe',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wollu',
            name='no_work',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wollu',
            name='shopping',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wollu',
            name='smoking',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wollu',
            name='something',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wollu',
            name='toilet',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wollu',
            name='turnover',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wollu',
            name='wind',
            field=models.IntegerField(null=True),
        ),
    ]
