# Generated by Django 4.1.4 on 2023-01-03 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_jobstats_alter_wollu_create_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobStats',
            new_name='Job_Stats',
        ),
    ]
