# Generated by Django 4.1.4 on 2023-03-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_stats_delete_job_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
